=== sotiriskarageorgopoulos/XML-exercises/DTDs/hotel_new.dtd
<!ELEMENT Hotel (Rooms,Offers)>
<!ELEMENT Rooms (Room+)>
<!ELEMENT Room (nameOfRoom,capacity,typesOfBeds,view+,comforts,prices,images)>
<!ELEMENT images (image)+>
<!ELEMENT typesOfBeds (single?,twin?,twinXL?,couch?)>
<!ELEMENT comforts (comfort*)>
<!ELEMENT prices (price*)>
<!ELEMENT nameOfRoom (#PCDATA)>
<!ELEMENT capacity EMPTY>
<!ELEMENT single (#PCDATA)>
<!ELEMENT twin (#PCDATA)>
<!ELEMENT twinXL (#PCDATA)>
<!ELEMENT couch (#PCDATA)>
<!ELEMENT view (#PCDATA)>
<!ELEMENT comfort (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT Offers (offer)*>
<!ELEMENT offer (duration)>
<!ELEMENT duration EMPTY>
<!ELEMENT image EMPTY>
<!NOTATION jpeg SYSTEM "image/jpeg">
<!ENTITY room1
         SYSTEM "./images/room1.jpeg"
         NDATA jpeg>
<!ENTITY room2
         SYSTEM "./images/room2.jpeg"
         NDATA jpeg>
<!ENTITY room3
         SYSTEM "./images/room3.jpeg"
         NDATA jpeg>
<!ENTITY room4
         SYSTEM "./images/room4.jpeg"
         NDATA jpeg>
<!ENTITY room5
         SYSTEM "./images/room5.jpeg"
         NDATA jpeg>
<!ENTITY room6
         SYSTEM "./images/room6.jpeg"
         NDATA jpeg>
<!ATTLIST image src ENTITY #REQUIRED>
<!ATTLIST capacity numOfPersons (1|2|3|4) #REQUIRED>
<!ATTLIST duration time_period CDATA #REQUIRED
                       from CDATA #REQUIRED
                       to CDATA #REQUIRED>
<!ATTLIST offer rooms_code IDREFS #REQUIRED
                offer_price CDATA #REQUIRED
                >
<!ATTLIST Hotel nameOfHotel CDATA #REQUIRED
                stars CDATA #REQUIRED>
<!ATTLIST Room idRoom ID #REQUIRED>
<!ATTLIST nameOfRoom suite (yes|no) #IMPLIED
                     floor CDATA #IMPLIED
                     wifi (yes|no) "yes">
<!ATTLIST comfort extra_charge (yes|no) "no">
<!ATTLIST price period CDATA #REQUIRED>

=== sotiriskarageorgopoulos/XML-exercises/hotel_room_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Hotel SYSTEM "./DTDs/hotel_new.dtd" []>
<Hotel nameOfHotel="Thanos Village" stars="4">
    <Rooms>
        <Room idRoom="R1">
            <nameOfRoom suite="no" floor="3" wifi="no">Odysseus</nameOfRoom>
            <capacity numOfPersons="4" />
            <typesOfBeds>
                <single>2</single>
                <twin>1</twin>
            </typesOfBeds>
            <view>Sea</view>
            <view>Mountain</view>
            <comforts>
                <comfort extra_charge="yes">Heating</comfort>
                <comfort>Breakfast</comfort>
            </comforts>
            <prices>
            </prices>
            <images>
                <image src="room1" />
            </images>
        </Room>
        <Room idRoom="R2">
            <nameOfRoom suite="yes" floor="4" wifi="no">Priapos</nameOfRoom>
            <capacity numOfPersons="2" />
            <typesOfBeds>
                <twin>1</twin>
                <couch>2</couch>
            </typesOfBeds>
            <view>Sea</view>
            <view>Mountain</view>
            <comforts>
                <comfort extra_charge="yes">Heating</comfort>
                <comfort>Breakfast</comfort>
                <comfort extra_charge="yes">Mini Bar</comfort>
            </comforts>
            <prices>
                <price period="High Season">90</price>
                <price period="Medium Season">65</price>
            </prices>
            <images>
                <image src="room2" />
            </images>
        </Room>
        <Room idRoom="R3">
            <nameOfRoom suite="no" floor="1" wifi="yes">Estia</nameOfRoom>
            <capacity numOfPersons="4" />
            <typesOfBeds>
                <single>1</single>
                <twinXL>1</twinXL>
                <couch>1</couch>
            </typesOfBeds>
            <view>Sea</view>
            <comforts>
                <comfort extra_charge="yes">Heating</comfort>
                <comfort>Breakfast</comfort>
                <comfort>Mini Bar</comfort>
                <comfort extra_charge="yes">Dinner</comfort>
            </comforts>
            <prices>
                <price period="High Season">70</price>
                <price period="Medium Season">50</price>
            </prices>
            <images>
                <image src="room3" />
            </images>
        </Room>
        <Room idRoom="R4">
            <nameOfRoom suite="no" floor="2" wifi="yes">Deus</nameOfRoom>
            <capacity numOfPersons="4" />
            <typesOfBeds>
                <twin>2</twin>
                <couch>1</couch>
            </typesOfBeds>
            <view>Sea</view>
            <comforts>
                <comfort extra_charge="yes">Heating</comfort>
                <comfort>Breakfast</comfort>
                <comfort>Mini Bar</comfort>
                <comfort extra_charge="yes">Dinner</comfort>
            </comforts>
            <prices>
                <price period="High Season">80</price>
                <price period="Medium Season">65</price>
            </prices>
            <images>
                <image src="room4" />
            </images>
        </Room>
        <Room idRoom="R5">
            <nameOfRoom suite="yes" floor="3" wifi="yes">Yra</nameOfRoom>
            <capacity numOfPersons="1" />
            <typesOfBeds>
                <single>1</single>
                <couch>1</couch>
            </typesOfBeds>
            <view>Sea</view>
            <view>Mountain</view>
            <comforts>
                <comfort extra_charge="yes">Heating</comfort>
                <comfort extra_charge="no">Breakfast</comfort>
                <comfort extra_charge="no">Mini Bar</comfort>
                <comfort extra_charge="no">Afternoon Coffee</comfort>
            </comforts>
            <prices>
                <price period="High Season">60</price>
                <price period="Medium Season">45</price>
            </prices>
            <images>
                <image src="room5"/>
            </images>
        </Room>
        <Room idRoom="R6">
            <nameOfRoom suite="yes" floor="5" wifi="yes">Aphrodite</nameOfRoom>
            <capacity numOfPersons="2" />
            <typesOfBeds>
                <twin>1</twin>
                <couch>1</couch>
            </typesOfBeds>
            <view>Sea</view>
            <view>Mountain</view>
            <comforts>
                <comfort extra_charge="yes">Heating</comfort>
                <comfort>Breakfast</comfort>
                <comfort extra_charge="yes">Mini Bar</comfort>
                <comfort>Afternoon Coffee</comfort>
            </comforts>
            <prices>
                <price period="High Season">90</price>
                <price period="Medium Season">75</price>
                <price period="Low Season">45</price>
            </prices>
            <images>
                <image src="room6"/>
            </images>
        </Room>
    </Rooms>
    <Offers>
        <offer rooms_code="R1" offer_price="50">
            <duration time_period="4" from="2020-07-02" to="2020-07-06" />
        </offer>
        <offer rooms_code="R2 R3" offer_price="60">
            <duration time_period="6" from="2020-08-04" to="2020-07-10" />
        </offer>
        <offer rooms_code="R5" offer_price="45">
            <duration time_period="2" from="2020-06-18" to="2020-06-20" />
        </offer>
        <offer rooms_code="R6" offer_price="65">
            <duration time_period="11" from="2020-06-02" to="2020-06-13" />
        </offer>
    </Offers>
</Hotel>
